### ISSUE TITLE
Wrong ministry name for UK

### ISSUE THREAD

**Issue by cmcaine** [chrismatix/free-iea-data#1]
Hi, thanks for making this tool, I hope that the campaign succeeds!

The email template says "Ministry for Industry, Energy, and Emissions Reduction", but the position is "Minister for Energy, Clean Growth and Climate Change".

https://www.gov.uk/government/ministers/minister-of-state--75

The template should also say Minister rather than Ministry.

**Comment by chrismatix** [comment]
Thank you very much for pointing this out! I have updated the text.
