### ISSUE TITLE
Improve Danish translation

### ISSUE THREAD

**Issue by jokkedk** [chrismatix/free-iea-data#3]
I'd like to suggest altering the Danish copy to improve the translation and readability. I am a native speaker.

> Til Dan Jørgensen
> 
> Jeg skriver dette for at opfordre dig til at bruge din indflydelse som Danmark’s IEA-repræsentant til at gøre IEA’s data tilgængeligt for alle
>
> Som du ved som minister af Energi-, Forsynings- og Klimaministeriet at forhindre klimaforandringer kræver en fælles forståelse baseret på korrekt klima og energi data.
>
> Det internationale energiråd som Danmark delvist betaler for, har dette høj-kvalitets data. Uheldigvis er det gemt bag en betalingsmur, som gør det utilgængeligt for mange forskere og journalister.
>
> IEA’s budget siger at omkring en femtedel at deres årlige budget (omkring 5 millioner euro) kommer fra salg af data. Dette mindre beløb retfærdiggør ikke betalingsmuren.
>
> Jeg spørger dig til at bruge din indflydelse til at fjerne kravet om at IEA er nødt til at finansiere en del af deres budget med salg af data og øge deres finansiering hvis nødvendigt
>
> For videre læsning og mere uddybende argumenter for at gøre IEA’s data frit tilgængeligt: https://ourworldindata.org/iea-open-data og https://www.nature.com/articles/d41586-021-02691-4
>
> Tak for din overvejelse og jeg ser frem til at høre fra dig snarest muligt.

Change to

> Til Dan Jørgensen
>
> Jeg skriver for at opfordre dig til at bruge din indflydelse som Danmarks IEA-repræsentant til at gøre IEAs data tilgængeligt for alle.
>
> Som Klima-, energi- og forsyningsminister ved du, at det kræver en fælles forståelse baseret på korrekt klima og energi data at forhindre klimaforandringer.
>
> Det Internationale Energiagentur (IEA), som Danmark delvist betaler for, har dette høj-kvalitets data. Uheldigvis er det gemt bag en betalingsmur, som gør det utilgængeligt for mange forskere og journalister.
>
> IEA’s budget fortæller at omkring en femtedel at deres årlige budget (omkring 5 millioner euro) kommer fra salg af data. Dette mindre beløb retfærdiggør ikke betalingsmuren.
>
> Jeg beder dig til at bruge din indflydelse til at fjerne nødvendigheden af at IEA finansierer en del af deres budget ved salg af data og øge betalingen hvis nødvendigt.
>
> Flere oplysninger og mere uddybende argumenter for at gøre IEA’s data frit tilgængeligt kan findes her: https://ourworldindata.org/iea-open-data og https://www.nature.com/articles/d41586-021-02691-4
>
> Tak for din overvejelse og jeg ser frem til at høre fra dig snarest muligt.

**Comment by chrismatix** [comment]
Thank you for the improvements. They are online now.
